# Generated by Django 5.0.1 on 2024-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="overtime_hours",
            field=models.FloatField(null=True),
        ),
    ]
