# Generated by Django 5.0.1 on 2024-04-04 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payroll_app", "0002_employee_overtime_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="overtime_pay",
        ),
    ]
