# Generated by Django 5.0.1 on 2024-04-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll_app", "0003_remove_employee_overtime_pay"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payslip",
            old_name="id_number",
            new_name="employee",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="date_range",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="deductions_health",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="deductions_tax",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="earnings_allowance",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="overtime",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="pag_ibig",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="sss",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="total_pay",
        ),
        migrations.AlterField(
            model_name="employee",
            name="id_number",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
