# Generated by Django 5.0.1 on 2024-04-08 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll_app", "0004_rename_id_number_payslip_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="overtime_pay",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="payslip",
            name="allowance",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="payslip",
            name="date_range",
            field=models.CharField(
                default=datetime.datetime(2000, 1, 1, 0, 0), max_length=25
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payslip",
            name="deductions_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payslip",
            name="gross_pay",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payslip",
            name="id_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payslip",
            name="net_pay",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payslip",
            name="overtime_pay",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="payslip",
            name="pag_ibig",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payslip",
            name="philhealth",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payslip",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payslip",
            name="sss",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payslip",
            name="total_pay",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="allowance",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="employee",
            name="overtime_hours",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="month",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="year",
            field=models.CharField(max_length=4),
        ),
    ]
