# Generated by Django 5.0.1 on 2024-04-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll_app", "0005_employee_overtime_pay_payslip_allowance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="pag_ibig",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="philhealth",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="sss",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
