# Generated by Django 5.0.1 on 2024-04-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payroll_app",
            "0006_alter_payslip_pag_ibig_alter_payslip_philhealth_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="allowance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="overtime_pay",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="rate",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="allowance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="deductions_tax",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="gross_pay",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="net_pay",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="overtime_pay",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="pag_ibig",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="philhealth",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="sss",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="total_pay",
            field=models.FloatField(null=True),
        ),
    ]
