# Generated by Django 5.0.1 on 2024-04-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payroll_app",
            "0007_alter_employee_allowance_alter_employee_overtime_pay_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="allowance",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="overtime_pay",
            field=models.FloatField(default=0, null=True),
        ),
    ]
