# Generated by Django 5.0.1 on 2024-04-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll_app", "0008_alter_payslip_allowance_alter_payslip_overtime_pay"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payslip",
            old_name="deductions_tax",
            new_name="tax",
        ),
        migrations.AddField(
            model_name="payslip",
            name="total_deductions",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="gross_pay",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="net_pay",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="rate",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="total_pay",
            field=models.FloatField(default=0, null=True),
        ),
    ]
