# Generated by Django 5.0.1 on 2024-04-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll_app", "0009_rename_deductions_tax_payslip_tax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="cycle_rate",
            field=models.FloatField(default=0),
        ),
    ]
