# Generated by Django 5.0.1 on 2024-04-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payroll_app",
            "0011_remove_payslip_net_pay_alter_employee_allowance_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="total_pay_desc",
            field=models.CharField(default="", max_length=300),
        ),
    ]
